"use client";

import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence, useScroll, useSpring } from "framer-motion";
import { ArrowRight, BrainCircuit, BriefcaseBusiness, Code2, ContactRound as Linkedin, ExternalLink, GitFork as Github, GraduationCap, Layers3, Mail, Menu, Server, Sparkles, Terminal, X } from "lucide-react";
import { RobotHero } from "./RobotHero";

const links = ["about", "skills", "projects", "experience", "contact"];
const reveal = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0, transition: { duration: .3, ease: [0.16, 1, 0.3, 1] as const } } };
const stagger = { hidden: {}, show: { transition: { staggerChildren: .07 } } };

type ButtonProps = React.AnchorHTMLAttributes<HTMLAnchorElement> & { variant?: "primary" | "secondary" | "ghost" };
function Button({ variant = "primary", className = "", children, ...props }: ButtonProps) {
  return <a className={`button ${variant} ${className}`} {...props}>{children}</a>;
}
function Badge({ children }: { children: React.ReactNode }) { return <span className="badge">{children}</span>; }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`card ${className}`}>{children}</div>; }
function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <motion.div className="section-heading" variants={reveal} initial="hidden" whileInView="show" viewport={{ once: true, amount: .35 }}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</motion.div>;
}
function AnimatedNumber({ value, suffix = "" }: { value: string; suffix?: string }) { return <span className="stat-value">{value}{suffix}</span>; }

type GraphNode = { label: string; detail?: string };
function NodeGraph({ nodes, compact = false }: { nodes: GraphNode[]; compact?: boolean }) {
  return <motion.div className={`node-graph ${compact ? "compact" : ""}`} variants={stagger} initial="hidden" whileInView="show" viewport={{ once: true, amount: .3 }}>
    {nodes.map((node, i) => <motion.div className="node-wrap" variants={reveal} key={node.label}>
      <div className="graph-node" tabIndex={0}><span>{String(i + 1).padStart(2, "0")}</span>{node.label}{node.detail && <small>{node.detail}</small>}</div>
      {i < nodes.length - 1 && <div className="edge"><i /></div>}
    </motion.div>)}
  </motion.div>;
}

const skills = [
  { title: "Programming", icon: Code2, copy: "Reliable foundations for AI products.", items: ["Python", "Java", "JavaScript", "SQL", "Bash / Shell", "OOP", "Asyncio"] },
  { title: "AI / ML", icon: BrainCircuit, copy: "From exploration to evaluated pipelines.", items: ["Machine Learning", "EDA", "LLMs", "Prompt Engineering", "Embeddings", "Semantic Search"] },
  { title: "GenAI Systems", icon: Sparkles, copy: "Grounded, tool-using intelligent systems.", items: ["RAG", "LangChain", "LangGraph", "Multi-Agent AI", "Memory", "Tool Routing"] },
  { title: "Backend", icon: Server, copy: "Production-minded APIs and persistence.", items: ["FastAPI", "Flask", "Django", "REST APIs", "PostgreSQL", "MySQL", "SQLite"] },
  { title: "Engineering", icon: Terminal, copy: "A practical shipping workflow.", items: ["Git", "GitHub", "PyTest", "Poetry", "Pipenv", "n8n", "Automation"] },
  { title: "Architecture", icon: Layers3, copy: "Systems designed around real constraints.", items: ["Backend Architecture", "Vector Databases", "API Design", "Data Structures", "Retrieval Pipelines"] },
];

const projects = [
  { title: "Production-Level Enterprise RAG System", kicker: "Retrieval intelligence", description: "An enterprise-grade document intelligence system for PDF ingestion, semantic retrieval, conversation memory, and grounded question answering.", problem: "Teams lose time searching fragmented internal documents and cannot trust ungrounded AI answers.", solution: "A traceable retrieval pipeline that chunks, embeds, ranks, and synthesizes evidence-backed responses.", tech: ["Python", "FastAPI", "LangChain", "PostgreSQL", "SQLite", "RAG"], features: ["PDF ingestion & chunking", "Semantic vector search", "Conversation memory", "Scalable retrieval pipeline"], graph: ["Documents", "Chunking", "Embeddings", "Vector DB", "Retriever", "LLM", "Answer"] },
  { title: "Personal AI Operating System", kicker: "Agentic automation", description: "A personal AI assistant that controls desktop applications, browser tasks, Gmail, files, and productivity workflows.", problem: "Everyday work is split across tools, interfaces, and repetitive manual steps.", solution: "An LLM-driven orchestration layer with memory and deliberate tool routing for real-world task execution.", tech: ["Python", "FastAPI", "LangGraph", "LangChain", "SQLite", "REST APIs"], features: ["Desktop and browser control", "Gmail and file workflows", "Long-lived memory", "Tool routing"], graph: ["User", "Planner", "Memory", "Tool Router", "Apps", "Result"] },
  { title: "Multi-Agent Research Assistant", kicker: "Collaborative reasoning", description: "A structured research workflow where specialist agents research, fact-check, summarize, and assemble reliable reports.", problem: "Single-pass research produces inconsistent coverage and weak verification.", solution: "A stateful graph coordinates specialists and makes every stage explicit and inspectable.", tech: ["LangGraph", "LangChain", "Python", "FastAPI"], features: ["Research agent", "Fact-checking loop", "Structured synthesis", "Report generation"], graph: ["Brief", "Research", "Fact Check", "Synthesis", "Report"] },
];

function Navbar() {
  const [open, setOpen] = useState(false); const [active, setActive] = useState("about");
  useEffect(() => { const obs = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && setActive(e.target.id)), { rootMargin: "-30% 0px -60%" }); links.forEach(x => { const e=document.getElementById(x); if(e) obs.observe(e); }); return () => obs.disconnect(); }, []);
  return <><nav className="nav"><a className="logo" href="#top"><b>MD</b><span>Mohamed Daheer</span></a><div className="desktop-links">{links.map(x => <a className={active === x ? "active" : ""} key={x} href={`#${x}`}>{x}{active === x && <motion.i layoutId="nav-pill" />}</a>)}</div><Button href="#contact" className="nav-cta">Let&apos;s Connect</Button><button className="menu-button" aria-label="Open menu" onClick={() => setOpen(true)}><Menu /></button></nav>
  <AnimatePresence>{open && <motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button aria-label="Close menu" onClick={() => setOpen(false)}><X /></button>{links.map((x,i) => <motion.a initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.07}} onClick={() => setOpen(false)} key={x} href={`#${x}`}>{x}</motion.a>)}</motion.div>}</AnimatePresence></>;
}

function ProjectModal({ project, close }: { project: typeof projects[number] | null; close: () => void }) {
  return <AnimatePresence>{project && <motion.div className="modal-backdrop" role="dialog" aria-modal="true" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}><motion.div className="modal" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} transition={{duration:.5,ease:[.16,1,.3,1]}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close case study"><X /></button><span className="eyebrow">Case study</span><h2>{project.title}</h2><div className="modal-grid"><div><h3>Overview</h3><p>{project.description}</p><h3>Problem</h3><p>{project.problem}</p><h3>Solution</h3><p>{project.solution}</p></div><div><h3>Architecture</h3><NodeGraph compact nodes={project.graph.map(label=>({label}))}/><h3>Technical implementation</h3><div className="badges">{project.tech.map(x=><Badge key={x}>{x}</Badge>)}</div><h3>Results</h3><p>A modular, production-oriented foundation built for observable retrieval, deliberate orchestration, and iterative evaluation.</p></div></div><Button href="https://github.com/mdaheer123-design" target="_blank">View GitHub <ExternalLink /></Button></motion.div></motion.div>}</AnimatePresence>;
}

export function Portfolio() {
  const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 120, damping: 24 }); const [project, setProject] = useState<typeof projects[number] | null>(null);
  const contributions = useMemo(() => Array.from({length:126},(_,i)=>((i*17+i*i*3+11)%5)),[]);
  return <main id="top"><motion.div className="progress" style={{scaleX:progress}}/><Navbar />
    <section className="hero"><div className="hero-grid"><motion.div className="hero-copy" initial="hidden" animate="show" variants={stagger}><motion.div variants={reveal} className="availability"><i/> Available for AI engineering opportunities</motion.div><motion.p variants={reveal} className="identity">Mohamed Daheer <span>/</span> AI / ML Engineer</motion.p><motion.h1 variants={reveal}>Building Intelligent<br/>Systems <em>with AI</em></motion.h1><motion.p variants={reveal} className="lead">AI / ML Engineer focused on Generative AI, RAG systems, intelligent agents, and production-oriented AI applications.</motion.p><motion.div variants={reveal} className="actions"><Button href="#projects">View Projects <ArrowRight /></Button><Button variant="secondary" href="#contact">Let&apos;s Connect</Button><a className="icon-link" href="https://github.com/mdaheer123-design" aria-label="GitHub"><Github /></a><a className="icon-link" href="https://www.linkedin.com/in/mdaheer" aria-label="LinkedIn"><Linkedin /></a></motion.div></motion.div>
      <motion.div className="hero-visual robot-visual" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5,ease:[.16,1,.3,1]}}><RobotHero /></motion.div></div></section>

    <section id="about"><div className="container"><SectionHeading eyebrow="About" title="Engineering AI That Solves Real Problems" copy="I turn emerging AI capabilities into practical, inspectable software systems."/><div className="about-grid"><motion.div className="about-copy" variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><p>I&apos;m an Artificial Intelligence & Data Science graduate focused on building useful AI systems with Python, LLMs, retrieval, agents, and modern backends.</p><p>My work sits at the intersection of intelligent orchestration and dependable software engineering: grounded RAG pipelines, tool-using assistants, backend APIs, memory, automation, and production-minded architecture.</p></motion.div><motion.div className="stat-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{once:true}}>{[["8.2","CGPA"],["AI & DS","Specialization"],["Python","Primary language"],["GenAI","Focus area"]].map(([v,l])=><motion.div variants={reveal} key={l}><Card><AnimatedNumber value={v}/><span>{l}</span></Card></motion.div>)}</motion.div></div></div></section>

    <section id="skills"><div className="container"><SectionHeading eyebrow="Skills" title="A Stack Built for Intelligent Products" copy="Broad enough to ship the product. Deep where AI systems demand rigor."/><motion.div className="skill-grid" variants={stagger} initial="hidden" whileInView="show" viewport={{once:true}}>{skills.map(s=><motion.div variants={reveal} key={s.title}><Card className="skill-card"><s.icon/><h3>{s.title}</h3><p>{s.copy}</p><div className="badges">{s.items.map(x=><Badge key={x}>{x}</Badge>)}</div></Card></motion.div>)}</motion.div></div></section>

    <section id="projects"><div className="container"><SectionHeading eyebrow="Selected work" title="AI Systems, Built End to End" copy="Projects designed around real problems, explicit architecture, and dependable execution."/><div className="project-list">{projects.map((p,i)=><motion.article className="project-card card" key={p.title} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true,amount:.2}}><div className="project-index">0{i+1}</div><div className="project-main"><span className="eyebrow">{p.kicker}</span><h3>{p.title}</h3><p>{p.description}</p><ul>{p.features.map(x=><li key={x}>{x}</li>)}</ul><div className="badges">{p.tech.map(x=><Badge key={x}>{x}</Badge>)}</div><div className="actions"><button className="button primary" onClick={()=>setProject(p)}>View Case Study <ArrowRight /></button><Button variant="secondary" href="https://github.com/mdaheer123-design" target="_blank">GitHub <Github /></Button></div></div><div className="project-graph"><NodeGraph compact nodes={p.graph.map(label=>({label}))}/></div></motion.article>)}</div></div></section>

    <section id="experience"><div className="container"><SectionHeading eyebrow="Experience" title="Applied AI Engineering"/><motion.div className="timeline" variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="timeline-meta"><span>6 months</span><span>Cavin Infotech</span></div><Card className="timeline-card"><BriefcaseBusiness/><span className="eyebrow">AI Intern</span><h3>Building practical AI applications</h3><p>Developed AI-powered applications with Python, FastAPI, and Large Language Models. Built enterprise RAG pipelines, designed backend APIs, integrated vector databases, optimized prompt workflows, and collaborated on automation solutions.</p><div className="badges">{["Python","FastAPI","LLMs","RAG","Vector DB","Automation"].map(x=><Badge key={x}>{x}</Badge>)}</div></Card></motion.div></div></section>

    <section><div className="container"><SectionHeading eyebrow="Architecture" title="How I Build AI Systems" copy="A clear path from user intent to grounded, observable execution."/><Card className="architecture"><NodeGraph nodes={[{label:"User",detail:"Intent & context"},{label:"Application",detail:"Experience layer"},{label:"API Layer",detail:"Contracts & auth"},{label:"Orchestrator",detail:"State & routing"},{label:"RAG / Agent",detail:"Grounding & action"},{label:"LLM",detail:"Reasoning"},{label:"Tools",detail:"External capability"},{label:"Database",detail:"Memory & records"}]}/></Card></div></section>

    <section><div className="container education-grid"><div><SectionHeading eyebrow="Education" title="Foundations in AI & Data Science"/><Card className="education"><GraduationCap/><div><h3>B.Tech - Artificial Intelligence & Data Science</h3><p>C.K. College of Engineering and Technology, Cuddalore</p></div><div><AnimatedNumber value="8.2" suffix="/10"/><span>CGPA</span></div></Card></div><div><SectionHeading eyebrow="Certifications" title="Continuous Learning"/><Card className="certs">{["Machine Learning with Python - Coursera","Introduction to Generative AI - Coursera","Data Analysis with Python - Coursera","Python Programming - Mimo"].map(x=><p key={x}><span>✓</span>{x}</p>)}</Card></div></div></section>

    <section><div className="container"><SectionHeading eyebrow="Open source" title="Building in Public" copy="Experiments, production-minded systems, and the work behind them."/><Card className="github-card"><div className="github-copy"><Github/><h3>mdaheer123-design</h3><p>Building practical AI systems in the open - from retrieval pipelines to agentic automation.</p><Button href="https://github.com/mdaheer123-design" target="_blank">View GitHub <ExternalLink /></Button></div><div className="contrib" aria-label="Contribution-style visualization">{contributions.map((v,i)=><i key={i} data-level={v}/>)}</div></Card></div></section>

    <section id="contact"><div className="container contact-grid"><div><span className="eyebrow">Contact</span><h2>Have an AI problem<br/>worth solving?</h2><p>Let&apos;s build something intelligent - grounded in a real use case and engineered to last.</p><div className="contact-links"><Button variant="secondary" href="mailto:mdaheer123@gmail.com"><Mail/> Email</Button><Button variant="secondary" href="https://github.com/mdaheer123-design"><Github/> GitHub</Button><Button variant="secondary" href="https://www.linkedin.com/in/mdaheer"><Linkedin/> LinkedIn</Button></div></div><form className="card" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const subject=encodeURIComponent(`Portfolio enquiry from ${data.get("name")}`);const body=encodeURIComponent(`From: ${data.get("email")}\n\n${data.get("message")}`);window.location.href=`mailto:mdaheer123@gmail.com?subject=${subject}&body=${body}`;}}><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Message<textarea required name="message" rows={5} placeholder="Tell me about the problem..."/></label><button className="button primary" type="submit">Send Message <ArrowRight/></button><p className="form-note">Prefer email? Write directly to mdaheer123@gmail.com</p></form></div></section>

    <footer><a className="logo" href="#top"><b>MD</b><span>Mohamed Daheer · AI / ML Engineer</span></a><p>© 2026 Mohamed Daheer</p><div><a href="https://github.com/mdaheer123-design" aria-label="GitHub"><Github/></a><a href="https://www.linkedin.com/in/mdaheer" aria-label="LinkedIn"><Linkedin/></a><a href="mailto:mdaheer123@gmail.com" aria-label="Email"><Mail/></a></div></footer><ProjectModal project={project} close={()=>setProject(null)}/></main>;
}
